[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common"}

uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4" }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "uuid", "postgres", "migrate", "chrono"]}